// leavePlanEmailService.ts
import transporter from "../utils/emailConfiguration";
import path from "path";
import fs from "fs";
import { format } from "date-fns";
interface LeavePlanEmailBody {
  start_date: any;
  buffer: any;
}

const sendLeavePlanEmail = async (body: LeavePlanEmailBody) => {
  const fromMailId = process.env.EMAIL_FROM;
  const { start_date, buffer } = body;
  const start = new Date(start_date);
  const months = format(start, "MMMM");
  const year = start?.getFullYear();
  try {
    const template = `<!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>Leave Plan Notification</title>
          <style>
           .footer{
           text-align:"center"
           }
          </style>
        </head>
        <body>
          <div class="content">
            <p class="greeting">Hi Management,</p>
            <p class="message">
              Attached, please find the leave plan for the team for the month of  <strong>[${months}/${year}]</strong>. This document outlines the scheduled leaves of each team member to ensure smooth operations and adequate coverage during this period.
            </p>
            <p class="message">
             If you have any questions or require further information, please feel free to reach out.
            </p>
            <p class="message">
            Thank you for your attention.
            </p>
            <p class="message">
              Best regards,<br />
              The Aalam Team
            </p>
            <p class="footer">
            <strong>Note:</strong>This email was automatically generated by the system. Please do not reply directly to this message.
            </p>
          </div>
        </body>
      </html>`;
    // Define the attachment path
    // Send the email with the attachment
    await transporter.transporter.sendMail({
      from: `${fromMailId}`,
      to: "jegan.karthi@aalamsoft.com",
      subject: ` Team Leave Plan for [${months}/${year}]`,
      html: template,
      attachments: [
        {
          filename: "Oct_leave_report.xlsx",
          //   path: filePath, // Path to the file attachment
          content: buffer,
          contentType:
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        },
      ],
    });

    console.log("Leave plan email sent successfully.");
    return {
      message: "Leave plan email sent successfully",
      status: true,
    };
  } catch (error) {
    console.log("Error sending leave plan email:", error);
    return {
      message: "Error sending leave plan email",
      status: false,
    };
  }
};
export default { sendLeavePlanEmail };
